# Server Configuration
server.port=8080
spring.application.name=coffee-house-backend

# Active Profile
spring.profiles.active=dev

# Enable MongoDB Auto-index Creation
spring.data.mongodb.auto-index-creation=true

# Logging Configuration
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.com.coffeehouse.backend=DEBUG

# Razorpay (set via environment variables, do not hardcode secrets)
razorpay.key.id=rzp_test_SMQeTuUogqH0VD
razorpay.key.secret=YXerdrKTuv8j0KuZuf2qQyt0


# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prasannakumar96009849@gmail.com
spring.mail.password=nftq rqqd rkiu bnyk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# Allow uploads up to 5MB (or increase as needed)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
