# MongoDB Connection (Development)
#spring.mongodb.uri=mongodb://localhost:27017/coffeehouse
# MongoDB Connection (Development)
spring.mongodb.uri=mongodb+srv://coffee_admin:20224207@cluster0.niheykq.mongodb.net/coffee_house_backend?retryWrites=true&w=majority